### ISSUE TITLE
Permissions issue accessing charts when Signalk security is enabled

### ISSUE THREAD

**Issue by zubenubi** [vokkim/tuktuk-chart-plotter#19]
Installed tuktuk 0.0.19 and charts-plugin 2.0.0 with latest signalk-server-node (v1.2.2). Enabled security and turned off 'Allow ReadOnly Access'. Subsequently tuktuk would not display the mbtiles charts. Investigated to discover that a request to /signalk/v1/api/resources/charts would generate a 401 error in this configuration. Confirmed that turning on 'ReadOnly Access' allowed the server to access the chart files.

See discussion on slack for details but it is believed that tuktuk is not passing along cookies to the '/signalk/v1/api/resources/charts' request.

**Comment by vokkim** [comment]
Fixed, thanks @tkurki 
Released `0.0.20`
